language: php

php:
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
    - composer self-update
    - composer install --dev --prefer-source --no-interaction --quiet

script:
  - vendor/bin/phpunit

